[[redirects]]
    from = "/api/*"
    to = "API_URL"
    force = true
    status = 200
    headers = {Bypass-Tunnel-Reminder = "please"}

[[headers]]
  for = "/api/*"
  [headers.values]
    Bypass-Tunnel-Reminder = "please"